const toys = [
  {
    toy: "toy1",
    title: "Іграшка 1",
    rating: 4.5,
    mainImage: "/products/product1.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "30$ / 1300₴",
    size: "25x55x12 см",
    material: "бавовна",
    availability: false,
    crafting: "21 день",
    features: "",
    collections: ["redhair_friends"],
  },
  {
    toy: "toy2",
    title: "Іграшка 2",
    rating: 4.1,
    mainImage: "/products/product2.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "25$ / 1100₴",
    size: "30x20x10 см",
    material: "поліестер",
    availability: true,
    crafting: "5 днів",
    features: "Має пищалку всередині",
    collections: ["pair_friends"],
  },
  {
    toy: "toy3",
    title: "Іграшка 3",
    rating: 4.8,
    mainImage: "/products/product3.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "35$ / 1550₴",
    size: "15x15x15 см",
    material: "натуральний каучук",
    availability: true,
    crafting: "3 дні",
    features: "Стійка до прокусування",
    collections: ["fantasy_friends"],
  },
  {
    toy: "toy4",
    title: "Іграшка 4",
    rating: 4.6,
    mainImage: "/products/product4.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "30$ / 1300₴",
    size: "40x25x8 см",
    material: "бавовна + нейлон",
    availability: false,
    crafting: "10 днів",
    features: "Інтерактивні елементи",
    collections: ["redhair_friends", "fantasy_friends"],
  },
  {
    toy: "toy5",
    title: "Іграшка 5",
    rating: 4.2,
    mainImage: "/products/product1.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "25$ / 1050₴",
    size: "30x20x10 см",
    material: "бавовна",
    availability: true,
    crafting: "7 днів",
    features: "Зносостійкий матеріал",
    collections: [],
  },
  {
    toy: "toy6",
    title: "Іграшка 6",
    rating: 5,
    mainImage: "/products/product2.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "35$ / 1450₴",
    size: "45x30x12 см",
    material: "бавовна + поліестер",
    availability: false,
    crafting: "14 днів",
    features: "Посилені шви",
    collections: ["pair_friends", "redhair_friends"],
  },
  {
    toy: "toy7",
    title: "Іграшка 7",
    rating: 4.9,
    mainImage: "/products/product3.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "20$ / 850₴",
    size: "20x15x6 см",
    material: "бавовна",
    availability: true,
    crafting: "5 днів",
    features: "Легка вага",
    collections: ["pair_friends"],
  },
  {
    toy: "toy8",
    title: "Іграшка 8",
    rating: 4.3,
    mainImage: "/products/product4.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "28$ / 1200₴",
    size: "35x25x9 см",
    material: "бавовна + гума",
    availability: true,
    crafting: "9 днів",
    features: "Текстурована поверхня",
    collections: ["fantasy_friends"],
  },
  {
    toy: "toy9",
    title: "Іграшка 9",
    rating: 4.5,
    mainImage: "/products/product1.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "22$ / 950₴",
    size: "28x18x8 см",
    material: "бавовна",
    availability: false,
    crafting: "6 днів",
    features: "Безпечна для зубів",
    collections: [],
  },
  {
    toy: "toy10",
    title: "Іграшка 10",
    rating: 4.8,
    mainImage: "/products/product2.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "32$ / 1350₴",
    size: "38x22x10 см",
    material: "бавовна + нейлон",
    availability: true,
    crafting: "11 днів",
    features: "Багатофункціональна",
    collections: ["redhair_friends"],
  },
  {
    toy: "toy11",
    title: "Іграшка 11",
    rating: 4.5,
    mainImage: "/products/product3.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "27$ / 1150₴",
    size: "33x21x9 см",
    material: "бавовна + поліестер",
    availability: true,
    crafting: "8 днів",
    features: "Додаткові елементи",
    collections: ["fantasy_friends", "pair_friends"],
  },
  {
    toy: "toy12",
    title: "Іграшка 12",
    rating: 5,
    mainImage: "/products/product4.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "36$ / 1500₴",
    size: "42x28x11 см",
    material: "бавовна + нейлон",
    availability: false,
    crafting: "13 днів",
    features: "Підвищена міцність",
    collections: [],
  },
  {
    toy: "toy13",
    title: "Іграшка 13",
    rating: 4.5,
    mainImage: "/products/product1.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "24$ / 1000₴",
    size: "30x20x7 см",
    material: "бавовна",
    availability: true,
    crafting: "7 днів",
    features: "Зручна форма",
    collections: ["redhair_friends"],
  },
  {
    toy: "toy14",
    title: "Іграшка 14",
    rating: 4.5,
    mainImage: "/products/product2.png",
    images: ["/cleaning.jpg", "/toy.png", "/banner-image.jpg"],
    description: "...",
    price: "34$ / 1400₴",
    size: "40x24x10 см",
    material: "бавовна + гума",
    availability: true,
    crafting: "12 днів",
    features: "Комбіновані матеріали",
    collections: ["pair_friends"],
  },
];

export default toys;
